USE jhoney;

DROP TABLE IF EXISTS DogFriend;
DROP TABLE IF EXISTS Dog;
DROP TABLE IF EXISTS Food;
DROP TABLE IF EXISTS FoodType;

CREATE TABLE FoodType
(
    Id INT IDENTITY PRIMARY KEY,
    Type VARCHAR(20) NOT NULL,        
);

CREATE TABLE Food
(
    Id INT IDENTITY PRIMARY KEY,
    TypeId INT NOT NULL,    
    Name VARCHAR(20) NOT NULL,
	LabelName VARCHAR(20),
    
    FOREIGN KEY (TypeId) REFERENCES FoodType(Id)        
);

CREATE TABLE Dog
(
    Id INT IDENTITY PRIMARY KEY,
    Likes INT NOT NULL,

    Name VARCHAR(20),
    Breed VARCHAR(20)    
    
    FOREIGN KEY (Likes) REFERENCES Food(Id)
);

CREATE TABLE DogFriend
(
    Id INT IDENTITY PRIMARY KEY,
	DogId INT,
    FriendId INT,
	
    FOREIGN KEY (DogId) REFERENCES Dog(Id),
	FOREIGN KEY (FriendId) REFERENCES Dog(Id)
);